//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputControllers/Menus.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MenusMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MenusMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Menus"",
    ""maps"": [
        {
            ""name"": ""Interactuar"",
            ""id"": ""02b03177-61ee-4320-a354-355df9981974"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""fc6f20d2-0b91-4647-ad42-9e490df8bf54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GoBack"",
                    ""type"": ""Button"",
                    ""id"": ""788df189-8ef0-4145-a09b-6b5e348badec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""56cbca93-3361-49b7-a581-1df103e43cc7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c15a813-17fc-4b5b-8a0d-002d3f5435b7"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""229ed34e-93a8-4cbc-b8e3-09fc31400af6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70bbeb50-5458-4a9d-9ef4-86d30b16717c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Interactuar
        m_Interactuar = asset.FindActionMap("Interactuar", throwIfNotFound: true);
        m_Interactuar_Pause = m_Interactuar.FindAction("Pause", throwIfNotFound: true);
        m_Interactuar_GoBack = m_Interactuar.FindAction("GoBack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Interactuar
    private readonly InputActionMap m_Interactuar;
    private IInteractuarActions m_InteractuarActionsCallbackInterface;
    private readonly InputAction m_Interactuar_Pause;
    private readonly InputAction m_Interactuar_GoBack;
    public struct InteractuarActions
    {
        private @MenusMap m_Wrapper;
        public InteractuarActions(@MenusMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_Interactuar_Pause;
        public InputAction @GoBack => m_Wrapper.m_Interactuar_GoBack;
        public InputActionMap Get() { return m_Wrapper.m_Interactuar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InteractuarActions set) { return set.Get(); }
        public void SetCallbacks(IInteractuarActions instance)
        {
            if (m_Wrapper.m_InteractuarActionsCallbackInterface != null)
            {
                @Pause.started -= m_Wrapper.m_InteractuarActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_InteractuarActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_InteractuarActionsCallbackInterface.OnPause;
                @GoBack.started -= m_Wrapper.m_InteractuarActionsCallbackInterface.OnGoBack;
                @GoBack.performed -= m_Wrapper.m_InteractuarActionsCallbackInterface.OnGoBack;
                @GoBack.canceled -= m_Wrapper.m_InteractuarActionsCallbackInterface.OnGoBack;
            }
            m_Wrapper.m_InteractuarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @GoBack.started += instance.OnGoBack;
                @GoBack.performed += instance.OnGoBack;
                @GoBack.canceled += instance.OnGoBack;
            }
        }
    }
    public InteractuarActions @Interactuar => new InteractuarActions(this);
    public interface IInteractuarActions
    {
        void OnPause(InputAction.CallbackContext context);
        void OnGoBack(InputAction.CallbackContext context);
    }
}
